### ISSUE TITLE
hook-helpers on GNU Elpa?

### ISSUE THREAD

**Issue by kaushalmodi** [sirikid/add-hook-x#1]
It would be nice to know how this differs from http://nongnu.org/hook-helpers-el/

**Comment by sirikid** [comment]
Thank you for feedback. I will add a comparison with hook-helpers in README.md.

**Comment by sirikid** [comment]
https://github.com/sirikid/add-hook-x#comparison-with-hook-helpers
@kaushalmodi, what do you think, I answered the question?

**Comment by kaushalmodi** [comment]
Thanks for elaborating and adding the README.
